# Generated by Django 4.1.4 on 2022-12-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_contact_alter_setting_facebook_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
    ]
