# Generated by Django 4.1.4 on 2022-12-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_setting_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
