# Generated by Django 4.1.4 on 2022-12-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content'),
        ),
    ]
