# Generated by Django 4.1.4 on 2022-12-25 19:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
    ]
