# Generated by Django 4.1.4 on 2022-12-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='konum',
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='fiyat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='content',
            name='gun',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
