# Generated by Django 4.1.4 on 2022-12-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_content_konum'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
